### ISSUE TITLE
Would love to install on Windows 10 Mobile, but not available for Mobile in the Store

### ISSUE THREAD

**Issue by ubinner** [chausner/TranslateWithDictCC#1]
Have installed on a Windows 10 Tablet and wonder, whether the UWP app scales enough to be run on a 5" Lumia 650 running the Anniversary version of Windows 10?

What triggers this question: currently not flagged as mobile in the store and thus not accessible from my phone.
![image](https://cloud.githubusercontent.com/assets/10513374/25903028/8cdcc260-359b-11e7-8425-b418980f1c2d.png)

Kind regards

**Comment by chausner** [comment]
Currently, the app scales quite poorly to smaller screens which is why I haven't made it available for phones. Some non-trivial changes in the layout would be required to make it look properly on smaller screens. This has rather low priority for me at the moment but I am open to contributions in case you or someone else wants to work on it.

**Comment by chausner** [comment]
Closing since Windows 10 Mobile is no longer supported.
